### ISSUE TITLE
How to get the env variables

### ISSUE THREAD

**Issue by olserra** [ng-ha/tinder#1]
Hello, I am trying to clone and run your project, already created an authentication with Google at Firebase, but not sure how to get the APIKEY there, and the other env variables needed. Can you help me, please?

**Comment by nthanhha** [comment]
Hi, when you create android/ios app, an API key is auto-created:
Create a Firebase project > Browser key auto-created
Create a Firebase Apple App > iOS key auto-created
Create a Firebase Android App > Android key auto-created.

You can get that API key in your console web

You can read more in this link https://firebase.google.com/docs/projects/api-keys

**Comment by nthanhha** [comment]
I consider this issue as resolved.
